// Copyright (c) 2023 Espresso Systems (espressosys.com)
// This file is part of the HyperPlonk library.

// You should have received a copy of the MIT License
// along with the HyperPlonk library. If not, see <https://mit-license.org/>.

//! This module implements the sum check protocol.

use crate::{
    poly_iop::structs::IOPVerifierState, IOPProof, IOPProverMessage, PolyIOP, PolyIOPErrors,
};
use ark_ff::PrimeField;
use ark_std::{end_timer, start_timer};
use backend::{SumCheckProver, VPAuxInfo, VirtualPolynomial};
use std::fmt::Debug;
use transcript::IOPTranscript;

mod verifier;

/// Trait for doing sum check protocols.
pub trait SumCheck<F: PrimeField> {
    type VPAuxInfo;

    type SumCheckProof: Clone + Debug + Default + PartialEq;
    type Transcript;
    type SumCheckSubClaim: Clone + Debug + Default + PartialEq;

    /// Extract sum from the proof
    fn extract_sum(proof: &Self::SumCheckProof) -> F;

    /// Initialize the system with a transcript
    ///
    /// This function is optional -- in the case where a SumCheck is
    /// an building block for a more complex protocol, the transcript
    /// may be initialized by this complex protocol, and passed to the
    /// SumCheck prover/verifier.
    fn init_transcript() -> Self::Transcript;

    /// Generate proof of the sum of polynomial over {0,1}^`num_vars`
    ///
    /// The polynomial is represented in the form of a VirtualPolynomial.
    /// Requires positive variable-count and degree metadata.
    fn prove<B: SumCheckProver<F>>(
        backend: &B,
        poly: &VirtualPolynomial<F, B::Mle>,
        transcript: &mut Self::Transcript,
    ) -> Result<Self::SumCheckProof, PolyIOPErrors>;

    /// Verify the claimed sum using the proof
    /// Validates point length, round count, and every round's degree-dependent
    /// width. Challenges, not cached proof-point coordinates, determine the
    /// returned subclaim point. The transcript state after an error is
    /// unspecified.
    fn verify(
        sum: F,
        proof: &Self::SumCheckProof,
        aux_info: &Self::VPAuxInfo,
        transcript: &mut Self::Transcript,
    ) -> Result<Self::SumCheckSubClaim, PolyIOPErrors>;
}

/// Trait for sum check protocol verifier side APIs.
pub trait SumCheckVerifier<F: PrimeField> {
    type VPAuxInfo;
    type ProverMessage;
    type Challenge;
    type Transcript;
    type SumCheckSubClaim;

    /// Initialize the verifier's state.
    fn verifier_init(index_info: &Self::VPAuxInfo) -> Self;

    /// Run verifier for the current round, given a prover message.
    ///
    /// Note that `verify_round_and_update_state` only samples and stores
    /// challenges; and update the verifier's state accordingly. The actual
    /// verifications are deferred (in batch) to `check_and_generate_subclaim`
    /// at the last step.
    fn verify_round_and_update_state(
        &mut self,
        prover_msg: &Self::ProverMessage,
        transcript: &mut Self::Transcript,
    ) -> Result<Self::Challenge, PolyIOPErrors>;

    /// This function verifies the deferred checks in the interactive version of
    /// the protocol; and generate the subclaim. Returns an error if the
    /// proof failed to verify.
    ///
    /// If the asserted sum is correct, then the multilinear polynomial
    /// evaluated at `subclaim.point` will be `subclaim.expected_evaluation`.
    /// Otherwise, it is highly unlikely that those two will be equal.
    /// Larger field size guarantees smaller soundness error.
    fn check_and_generate_subclaim(
        &self,
        asserted_sum: &F,
    ) -> Result<Self::SumCheckSubClaim, PolyIOPErrors>;
}

/// A SumCheckSubClaim is a claim generated by the verifier at the end of
/// verification when it is convinced.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SumCheckSubClaim<F: PrimeField> {
    /// the multi-dimensional point that this multilinear extension is evaluated
    /// to
    pub point: Vec<F>,
    /// the expected evaluation
    pub expected_evaluation: F,
}

impl<F: PrimeField> SumCheck<F> for PolyIOP<F> {
    type SumCheckProof = IOPProof<F>;
    type VPAuxInfo = VPAuxInfo<F>;
    type SumCheckSubClaim = SumCheckSubClaim<F>;
    type Transcript = IOPTranscript<F>;

    fn extract_sum(proof: &Self::SumCheckProof) -> F {
        let start = start_timer!(|| "extract sum");
        let res = proof.proofs[0].evaluations[0] + proof.proofs[0].evaluations[1];
        end_timer!(start);
        res
    }

    fn init_transcript() -> Self::Transcript {
        let start = start_timer!(|| "init transcript");
        let res = IOPTranscript::<F>::new(b"Initializing SumCheck transcript");
        end_timer!(start);
        res
    }

    fn prove<B: SumCheckProver<F>>(
        backend: &B,
        poly: &VirtualPolynomial<F, B::Mle>,
        transcript: &mut Self::Transcript,
    ) -> Result<Self::SumCheckProof, PolyIOPErrors> {
        let start = start_timer!(|| "sum check prove");
        if poly.aux_info.num_variables == 0 || poly.aux_info.max_degree == 0 {
            return Err(PolyIOPErrors::InvalidParameters(
                "SumCheck requires positive variable count and degree.".to_string(),
            ));
        }
        poly.aux_info.max_degree.checked_add(1).ok_or_else(|| {
            PolyIOPErrors::InvalidParameters("SumCheck degree is too large.".to_string())
        })?;

        transcript.append_serializable_element(b"aux info", &poly.aux_info)?;

        let mut prover_state = backend.prover_init(poly)?;
        let mut challenge = None;
        let mut prover_msgs = Vec::with_capacity(poly.aux_info.num_variables);
        // sampled randomness derived from the transcript
        let mut point = Vec::with_capacity(poly.aux_info.num_variables);
        for _ in 0..poly.aux_info.num_variables {
            let prover_msg = IOPProverMessage::new(
                backend.prove_round_and_update_state(&mut prover_state, &challenge)?,
            );
            transcript.append_serializable_element(b"prover msg", &prover_msg)?;
            prover_msgs.push(prover_msg);
            let next_challenge = transcript.get_and_append_challenge(b"Internal round")?;
            // pushing each challenge point, including the last one, to the proof
            point.push(next_challenge);
            challenge = Some(next_challenge);
        }

        end_timer!(start);
        Ok(IOPProof {
            point,
            proofs: prover_msgs,
        })
    }

    fn verify(
        claimed_sum: F,
        proof: &Self::SumCheckProof,
        aux_info: &Self::VPAuxInfo,
        transcript: &mut Self::Transcript,
    ) -> Result<Self::SumCheckSubClaim, PolyIOPErrors> {
        let start = start_timer!(|| "sum check verify");
        let num_variables = aux_info.num_variables;
        if num_variables == 0 || aux_info.max_degree == 0 {
            return Err(PolyIOPErrors::InvalidParameters(
                "SumCheck requires positive variable count and degree.".to_string(),
            ));
        }
        let round_width = aux_info.max_degree.checked_add(1).ok_or_else(|| {
            PolyIOPErrors::InvalidParameters("SumCheck degree is too large.".to_string())
        })?;
        if proof.point.len() != num_variables || proof.proofs.len() != num_variables {
            return Err(PolyIOPErrors::InvalidProof(format!(
                "incorrect SumCheck dimensions: point {}, rounds {}, expected {}",
                proof.point.len(),
                proof.proofs.len(),
                num_variables
            )));
        }
        for message in &proof.proofs {
            if message.evaluations.len() != round_width {
                return Err(PolyIOPErrors::InvalidProof(format!(
                    "incorrect number of evaluations: {} vs {}",
                    message.evaluations.len(),
                    round_width
                )));
            }
        }

        transcript.append_serializable_element(b"aux info", aux_info)?;
        let mut verifier_state = IOPVerifierState::verifier_init(aux_info);
        for prover_msg in &proof.proofs {
            transcript.append_serializable_element(b"prover msg", prover_msg)?;
            IOPVerifierState::verify_round_and_update_state(
                &mut verifier_state,
                prover_msg,
                transcript,
            )?;
        }

        let res = IOPVerifierState::check_and_generate_subclaim(&verifier_state, &claimed_sum);

        end_timer!(start);
        res
    }
}

#[cfg(all(test, feature = "cpu"))]
mod test {
    use super::*;
    use ark_bls12_381::Fr;
    use ark_ff::UniformRand;
    use ark_poly::{DenseMultilinearExtension, MultilinearExtension};
    use ark_std::test_rng;
    use backend::{cpu::CpuBackend, BackendError, MleBackend};
    use std::sync::Arc;

    #[test]
    fn test_prover_rejects_invalid_metadata() -> Result<(), PolyIOPErrors> {
        for (num_variables, max_degree) in [(2, 0), (0, 1), (2, usize::MAX)] {
            let mut poly =
                VirtualPolynomial::<Fr, Arc<DenseMultilinearExtension<Fr>>>::new(num_variables);
            poly.aux_info.max_degree = max_degree;
            let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
            transcript.append_message(b"testing", b"metadata rejection")?;
            assert!(matches!(
                <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript),
                Err(PolyIOPErrors::InvalidParameters(_))
            ));
            assert!(matches!(
                CpuBackend.prover_init(&poly),
                Err(BackendError::InvalidParameters(_))
            ));
        }
        Ok(())
    }

    #[test]
    fn test_positive_degree_constant_values_are_supported() -> Result<(), PolyIOPErrors> {
        let mle = Arc::new(DenseMultilinearExtension::from_evaluations_vec(
            2,
            vec![Fr::from(5u64); 4],
        ));
        let poly = VirtualPolynomial::new_from_mle(&mle, Fr::from(1u64));
        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let proof = <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript)?;
        let mut verifier_transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let subclaim = <PolyIOP<Fr> as SumCheck<Fr>>::verify(
            Fr::from(20u64),
            &proof,
            &poly.aux_info,
            &mut verifier_transcript,
        )?;
        assert_eq!(subclaim.expected_evaluation, Fr::from(5u64));
        assert_eq!(
            CpuBackend.evaluate_vp(&poly, &subclaim.point)?,
            subclaim.expected_evaluation
        );
        Ok(())
    }

    #[test]
    fn test_sumcheck_rejects_malformed_shape() -> Result<(), PolyIOPErrors> {
        let mle = Arc::new(DenseMultilinearExtension::from_evaluations_vec(
            2,
            vec![
                Fr::from(1u64),
                Fr::from(2u64),
                Fr::from(3u64),
                Fr::from(4u64),
            ],
        ));
        let poly = VirtualPolynomial::new_from_mle(&mle, Fr::from(1u64));
        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let proof = <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript)?;
        let mut malformed = vec![IOPProof::default()];
        for rounds in [0, 1, 3] {
            let mut candidate = proof.clone();
            candidate.proofs.resize(rounds, proof.proofs[0].clone());
            malformed.push(candidate);
        }
        for point_length in [0, 1, 3] {
            let mut candidate = proof.clone();
            candidate.point.resize(point_length, Fr::from(0u64));
            malformed.push(candidate);
        }
        for round in 0..2 {
            for width in [0, 1, 3] {
                let mut candidate = proof.clone();
                candidate.proofs[round]
                    .evaluations
                    .resize(width, Fr::from(0u64));
                malformed.push(candidate);
            }
        }
        for candidate in malformed {
            let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
            transcript.append_message(b"testing", b"shape rejection")?;
            assert!(matches!(
                <PolyIOP<Fr> as SumCheck<Fr>>::verify(
                    Fr::from(10u64),
                    &candidate,
                    &poly.aux_info,
                    &mut transcript,
                ),
                Err(PolyIOPErrors::InvalidProof(_))
            ));
        }
        for (num_variables, max_degree) in [(0, 1), (2, 0), (2, usize::MAX)] {
            let mut aux_info = poly.aux_info.clone();
            aux_info.num_variables = num_variables;
            aux_info.max_degree = max_degree;
            let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
            transcript.append_message(b"testing", b"metadata rejection")?;
            assert!(matches!(
                <PolyIOP<Fr> as SumCheck<Fr>>::verify(
                    Fr::from(10u64),
                    &proof,
                    &aux_info,
                    &mut transcript,
                ),
                Err(PolyIOPErrors::InvalidParameters(_))
            ));
        }
        // Only transcript-derived challenges determine the returned subclaim.
        let mut altered_point = proof.clone();
        altered_point.point.fill(Fr::from(0u64));
        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let subclaim = <PolyIOP<Fr> as SumCheck<Fr>>::verify(
            Fr::from(10u64),
            &altered_point,
            &poly.aux_info,
            &mut transcript,
        )?;
        assert_eq!(subclaim.point, proof.point);
        assert_eq!(
            CpuBackend.evaluate_vp(&poly, &subclaim.point)?,
            subclaim.expected_evaluation
        );
        Ok(())
    }

    #[test]
    fn test_direct_verifier_rejects_invalid_rounds() -> Result<(), PolyIOPErrors> {
        use crate::IOPProverMessage;

        let aux_info = VPAuxInfo {
            num_variables: 2,
            max_degree: 0,
            phantom: std::marker::PhantomData::<Fr>,
        };
        for (num_variables, max_degree) in [(0, 1), (2, 0), (2, usize::MAX)] {
            let mut aux_info = aux_info.clone();
            aux_info.num_variables = num_variables;
            aux_info.max_degree = max_degree;
            let mut state = IOPVerifierState::verifier_init(&aux_info);
            let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
            transcript.append_message(b"testing", b"metadata rejection")?;
            assert!(matches!(
                state.verify_round_and_update_state(
                    &IOPProverMessage::new(vec![Fr::from(0u64); 2]),
                    &mut transcript,
                ),
                Err(PolyIOPErrors::InvalidParameters(_))
            ));
            assert!(matches!(
                state.check_and_generate_subclaim(&Fr::from(0u64)),
                Err(PolyIOPErrors::InvalidParameters(_))
            ));
        }
        let mut aux_info = aux_info;
        aux_info.max_degree = 1;
        for width in [0, 1, 3] {
            let mut state = IOPVerifierState::verifier_init(&aux_info);
            let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
            transcript.append_message(b"testing", b"round rejection")?;
            assert!(matches!(
                state.verify_round_and_update_state(
                    &IOPProverMessage::new(vec![Fr::from(0u64); width]),
                    &mut transcript,
                ),
                Err(PolyIOPErrors::InvalidProof(_))
            ));
        }
        for width in [0, 1, 3] {
            let mut state = IOPVerifierState::verifier_init(&aux_info);
            state.finished = true;
            state.polynomials_received = vec![vec![Fr::from(0u64); width]; 2];
            state.challenges = vec![Fr::from(2u64); 2];
            assert!(matches!(
                state.check_and_generate_subclaim(&Fr::from(0u64)),
                Err(PolyIOPErrors::InvalidProof(_))
            ));
        }
        for (rounds, challenges) in [(0, 2), (1, 2), (3, 2), (2, 0), (2, 1), (2, 3)] {
            let mut state = IOPVerifierState::verifier_init(&aux_info);
            state.finished = true;
            state.polynomials_received = vec![vec![Fr::from(0u64); 2]; rounds];
            state.challenges = vec![Fr::from(2u64); challenges];
            assert!(matches!(
                state.check_and_generate_subclaim(&Fr::from(0u64)),
                Err(PolyIOPErrors::InvalidVerifier(_))
            ));
        }
        aux_info.num_variables = 1;
        aux_info.max_degree = 0;
        let mut state = IOPVerifierState::verifier_init(&aux_info);
        state.finished = true;
        state.polynomials_received = vec![vec![Fr::from(0u64)]];
        state.challenges = vec![Fr::from(2u64)];
        assert!(matches!(
            state.check_and_generate_subclaim(&Fr::from(0u64)),
            Err(PolyIOPErrors::InvalidParameters(_))
        ));
        Ok(())
    }

    fn test_sumcheck(
        nv: usize,
        num_multiplicands_range: (usize, usize),
        num_products: usize,
    ) -> Result<(), PolyIOPErrors> {
        let mut rng = test_rng();
        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();

        let (poly, asserted_sum) =
            VirtualPolynomial::rand(nv, num_multiplicands_range, num_products, &mut rng)?;
        let proof = <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript)?;
        let poly_info = poly.aux_info.clone();
        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let subclaim = <PolyIOP<Fr> as SumCheck<Fr>>::verify(
            asserted_sum,
            &proof,
            &poly_info,
            &mut transcript,
        )?;
        assert!(
            CpuBackend.evaluate_vp(&poly, &subclaim.point).unwrap() == subclaim.expected_evaluation,
            "wrong subclaim"
        );
        Ok(())
    }

    fn test_sumcheck_internal(
        nv: usize,
        num_multiplicands_range: (usize, usize),
        num_products: usize,
    ) -> Result<(), PolyIOPErrors> {
        let mut rng = test_rng();
        let (poly, asserted_sum) =
            VirtualPolynomial::<Fr, _>::rand(nv, num_multiplicands_range, num_products, &mut rng)?;
        let poly_info = poly.aux_info.clone();
        let mut prover_state = CpuBackend.prover_init(&poly)?;
        let mut verifier_state = IOPVerifierState::verifier_init(&poly_info);
        let mut challenge = None;
        let mut transcript = IOPTranscript::new(b"a test transcript");
        transcript
            .append_message(b"testing", b"initializing transcript for testing")
            .unwrap();
        for _ in 0..poly.aux_info.num_variables {
            let prover_message = IOPProverMessage::new(
                CpuBackend
                    .prove_round_and_update_state(&mut prover_state, &challenge)
                    .unwrap(),
            );

            challenge = Some(
                IOPVerifierState::verify_round_and_update_state(
                    &mut verifier_state,
                    &prover_message,
                    &mut transcript,
                )
                .unwrap(),
            );
        }
        let subclaim =
            IOPVerifierState::check_and_generate_subclaim(&verifier_state, &asserted_sum)
                .expect("fail to generate subclaim");
        assert!(
            CpuBackend.evaluate_vp(&poly, &subclaim.point).unwrap() == subclaim.expected_evaluation,
            "wrong subclaim"
        );
        Ok(())
    }

    #[test]
    fn test_prover_preserves_input_polynomial() -> Result<(), PolyIOPErrors> {
        let mle = Arc::new(DenseMultilinearExtension::from_evaluations_vec(
            2,
            vec![
                Fr::from(2u64),
                Fr::from(3u64),
                Fr::from(5u64),
                Fr::from(7u64),
            ],
        ));
        let mut poly = VirtualPolynomial::new_from_mle(&mle, Fr::from(2u64));
        poly.add_mle_list([mle.clone(), mle.clone()], Fr::from(3u64))?;
        let point = [Fr::from(2u64), Fr::from(3u64)];
        let original_evaluation = CpuBackend.evaluate_vp(&poly, &point)?;
        let asserted_sum = mle
            .evaluations
            .iter()
            .map(|value| Fr::from(2u64) * value + Fr::from(3u64) * value * value)
            .sum();

        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let proof = <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript)?;
        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let subclaim = <PolyIOP<Fr> as SumCheck<Fr>>::verify(
            asserted_sum,
            &proof,
            &poly.aux_info,
            &mut transcript,
        )?;
        assert_eq!(proof.point, subclaim.point);
        assert_eq!(
            CpuBackend.evaluate_vp(&poly, &subclaim.point)?,
            subclaim.expected_evaluation
        );
        assert_eq!(CpuBackend.evaluate_vp(&poly, &point)?, original_evaluation);
        assert!(Arc::ptr_eq(&poly.flattened_ml_extensions()[0], &mle));

        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let repeated_proof =
            <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript)?;
        assert_eq!(proof, repeated_proof);

        poly.mul_by_mle(mle.clone(), Fr::from(1u64))?;
        assert_eq!(poly.flattened_ml_extensions().len(), 1);
        assert_eq!(
            CpuBackend.evaluate_vp(&poly, &point)?,
            original_evaluation * CpuBackend.evaluate_mle(&mle, &point)?
        );
        Ok(())
    }

    #[test]
    fn test_trivial_polynomial() -> Result<(), PolyIOPErrors> {
        let nv = 1;
        let num_multiplicands_range = (4, 13);
        let num_products = 5;

        test_sumcheck(nv, num_multiplicands_range, num_products)?;
        test_sumcheck_internal(nv, num_multiplicands_range, num_products)
    }
    #[test]
    fn test_normal_polynomial() -> Result<(), PolyIOPErrors> {
        let nv = 12;
        let num_multiplicands_range = (4, 9);
        let num_products = 5;

        test_sumcheck(nv, num_multiplicands_range, num_products)?;
        test_sumcheck_internal(nv, num_multiplicands_range, num_products)
    }
    #[test]
    fn zero_polynomial_should_error() {
        let nv = 0;
        let num_multiplicands_range = (4, 13);
        let num_products = 5;

        assert!(test_sumcheck(nv, num_multiplicands_range, num_products).is_err());
        assert!(test_sumcheck_internal(nv, num_multiplicands_range, num_products).is_err());
    }

    #[test]
    fn test_extract_sum() -> Result<(), PolyIOPErrors> {
        let mut rng = test_rng();
        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let (poly, asserted_sum) = VirtualPolynomial::<Fr, _>::rand(8, (3, 4), 3, &mut rng)?;

        let proof = <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript)?;
        assert_eq!(
            <PolyIOP<Fr> as SumCheck<Fr>>::extract_sum(&proof),
            asserted_sum
        );
        Ok(())
    }

    #[test]
    /// Test that the memory usage of shared-reference is linear to number of
    /// unique MLExtensions instead of total number of multiplicands.
    fn test_shared_reference() -> Result<(), PolyIOPErrors> {
        let mut rng = test_rng();
        let ml_extensions: Vec<_> = (0..5)
            .map(|_| Arc::new(DenseMultilinearExtension::<Fr>::rand(8, &mut rng)))
            .collect();
        let mut poly = VirtualPolynomial::new(8);
        poly.add_mle_list(
            vec![
                ml_extensions[2].clone(),
                ml_extensions[3].clone(),
                ml_extensions[0].clone(),
            ],
            Fr::rand(&mut rng),
        )?;
        poly.add_mle_list(
            vec![
                ml_extensions[1].clone(),
                ml_extensions[4].clone(),
                ml_extensions[4].clone(),
            ],
            Fr::rand(&mut rng),
        )?;
        poly.add_mle_list(
            vec![
                ml_extensions[3].clone(),
                ml_extensions[2].clone(),
                ml_extensions[1].clone(),
            ],
            Fr::rand(&mut rng),
        )?;
        poly.add_mle_list(
            vec![ml_extensions[0].clone(), ml_extensions[0].clone()],
            Fr::rand(&mut rng),
        )?;
        poly.add_mle_list(vec![ml_extensions[4].clone()], Fr::rand(&mut rng))?;

        assert_eq!(poly.flattened_ml_extensions().len(), 5);

        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let poly_info = poly.aux_info.clone();
        let proof = <PolyIOP<Fr> as SumCheck<Fr>>::prove(&CpuBackend, &poly, &mut transcript)?;
        let asserted_sum = <PolyIOP<Fr> as SumCheck<Fr>>::extract_sum(&proof);

        let mut transcript = <PolyIOP<Fr> as SumCheck<Fr>>::init_transcript();
        let subclaim = <PolyIOP<Fr> as SumCheck<Fr>>::verify(
            asserted_sum,
            &proof,
            &poly_info,
            &mut transcript,
        )?;
        assert!(
            CpuBackend.evaluate_vp(&poly, &subclaim.point)? == subclaim.expected_evaluation,
            "wrong subclaim"
        );
        Ok(())
    }
}
