[package]
name = "hyperplonk"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backend = { path = "../backend", default-features = false }
ark-ec = { version = "^0.6.0", default-features = false, features = ["parallel"] }
ark-ff = { version = "^0.6.0", default-features = false, features = ["parallel"] }
ark-poly = { version = "^0.6.0", default-features = false, features = ["parallel"] }
ark-serialize = { version = "^0.6.0", default-features = false, features = [ "derive" ] }
ark-std = { version = "^0.6.0", default-features = false, features = ["parallel"] }
displaydoc = { version = "0.2.3", default-features = false }
rayon = { version = "1.5.2", default-features = false }
subroutines = { path = "../subroutines", default-features = false }
transcript = { path = "../transcript" }

[dev-dependencies]
ark-bls12-381 = { version = "0.6.0", default-features = false, features = [ "curve" ] }
# Benchmarks
[[bench]]
name = "hyperplonk-benches"
path = "benches/bench.rs"
harness = false
required-features = ["cpu"]

[features]
default = ["cpu"]
cpu = ["backend/cpu", "subroutines/cpu"]
print-trace = [ 
    "ark-std/print-trace",
    "backend/print-trace",
    "subroutines/print-trace"
    ] 
